/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajopracticoobligatorio6;

import java.util.TreeSet;

/**
 *
 * @author JULIANA
 */
public class Menu extends javax.swing.JFrame {
    public static TreeSet<Producto> listaProductos = new TreeSet<>();
    public Menu() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmRubro = new javax.swing.JMenuItem();
        jmNombre = new javax.swing.JMenuItem();
        jmPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        jmProductos.setText("Productos");
        jmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jmProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jmRubro.setText("Por rubro..");
        jmRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jmRubro);

        jmNombre.setText("Por nombre..");
        jmNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jmNombre);

        jmPrecio.setText("Por precio..");
        jmPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jmPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNombreActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorNombreView busqueda = new BusquedaPorNombreView();
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        escritorio.moveToFront(busqueda);
    }//GEN-LAST:event_jmNombreActionPerformed

    private void jmRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorRubro busqueda = new BusquedaPorRubro();
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        escritorio.moveToFront(busqueda);
    }//GEN-LAST:event_jmRubroActionPerformed

    private void jmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ProductoInternalFrame busqueda = new ProductoInternalFrame();
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        escritorio.moveToFront(busqueda);
    }//GEN-LAST:event_jmProductosActionPerformed

    private void jmPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorPrecio busqueda= new BusquedaPorPrecio();
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        escritorio.moveToFront(busqueda);
    }//GEN-LAST:event_jmPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmNombre;
    private javax.swing.JMenuItem jmPrecio;
    private javax.swing.JMenuItem jmProductos;
    private javax.swing.JMenuItem jmRubro;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
        listaProductos.add(new Producto(1,"Azucar por 1Kg",800.50,10,"Comestible"));
        listaProductos.add(new Producto(2,"Yerba playadito 1Kg",1500.50,20,"Comestible"));
        listaProductos.add(new Producto(3,"Aceite Cocinero",950,5,"Comestible"));
        listaProductos.add(new Producto(5,"Detergente Magistral",600,10,"Limpieza"));
        listaProductos.add(new Producto(6,"Lavandina Ayudin",300,20,"Limpieza"));
        listaProductos.add(new Producto(7,"Cif liquido",1300,7,"Limpieza"));
        listaProductos.add(new Producto(8,"Perfume Paula",7000,3,"Perfumeria"));
        listaProductos.add(new Producto(9,"Crema Dermaglos",6000,2,"Perfumeria"));
        listaProductos.add(new Producto(10,"Desodorante Dove",1300,5,"Perfumeria"));
        
    }
}
